document:
  name: 05_Introduzione alla metodologia per la valutazione della maturità digitale degli istituti culturali
  description: |
    Le Linee guida 5 illustra i modelli di digital maturity assessment adottabili per gli istituti culturali, evidenziandone le opportunità di applicazione al patrimonio pubblico.
  tags:
      - patrimonio culturale digitale
      - digitalizzazione
      - digital transformation
      - maturità digitale
